### ISSUE TITLE
Build failure on ubuntu:20.04

### ISSUE THREAD

**Issue by srcshelton** [mixtile-rockchip/mixtile-clusterbox-mt7620a-openwrt#1]
Following the README.md build instructions to the letter and without having changed anything in the checked-out repo, at this point in time the build eventually fails with:

```
# ./build.sh all
...
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-theme-bootstrap for luci
 * pkg_hash_fetch_best_installation_candidate: Packages for luci found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci.
 * resolve_conffiles: Existing conffile /root/mixtile-clusterbox-mt7620a-openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/etc/sudoers is different from the conffile in the new package. The new conffile will be placed at /root/mixtile-clusterbox-mt7620a-openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/etc/sudoers-opkg.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/root/mixtile-clusterbox-mt7620a-openwrt'
make[1]: *** [package/Makefile:111: /root/mixtile-clusterbox-mt7620a-openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/root/mixtile-clusterbox-mt7620a-openwrt'
make: *** [/root/mixtile-clusterbox-mt7620a-openwrt/include/toplevel.mk:230: world] Error 2
```

**Comment by Buyuliang** [comment]
It is recommended to select the configuration file before compiling again,  you can try it.

./build.sh cluster-box-config

./build.sh feeds_update

./build.sh feeds_install

./build.sh all

**Comment by srcshelton** [comment]
That worked!

Comparing the repo [README.md](https://github.com/mixtile-rockchip/mixtile-clusterbox-mt7620a-openwrt/blob/v110/README.md) and your instructions above, it looks as if other than the order the commands are issued in, `./build.sh feeds_update` is missing from `README.md` - should this be added/updated?

(… by the way, is the repeated use of _lunch_ in [build.sh](https://github.com/mixtile-rockchip/mixtile-clusterbox-mt7620a-openwrt/blob/102f36ee8491454edd5c98716b05ba33995bd697/build.sh#L44) a typo of "_launch_"?)

**Comment by Buyuliang** [comment]
Yes, your understanding is correct. feeds_update is missing. Thank you for reminding me and I will improve this script
